# Generated by Django 3.2 on 2021-05-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, choices=[('HQ', 'HQ'), ('Shatila', 'Shatila'), ('Tripoli', 'Tripoli'), ('Bekaa', 'Bekaa'), ('Nabaa', 'Nabaa'), ('Other', 'Other')], max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('project', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=20)),
                ('invoice', models.FileField(upload_to='invoice')),
                ('grn', models.FileField(upload_to='grn')),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('Samsung', 'Lenovo'), ('Huawei', 'Huawei'), ('Lenovo', 'Lenovo'), ('Other', 'Other')], max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('handover_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('Stock', 'Stock'), ('in_use', 'in_use'), ('Maintenance', 'Maintenance'), ('Depreciated', 'Depreciated')], default='Stock', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('employee_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
                ('order_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
            ],
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_number', models.CharField(max_length=100, unique=True)),
                ('line_number', models.CharField(max_length=100, unique=True)),
                ('sim_type', models.CharField(choices=[('VPN', 'VPN'), ('DATA', 'DATA')], max_length=20)),
                ('status', models.CharField(choices=[('Stock', 'Stock'), ('in_use', 'in_use')], default='Stock', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('employee_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Stock', 'Stock'), ('in_use', 'in_use'), ('Maintenance', 'Maintenance'), ('Depreciated', 'Depreciated')], default='Stock', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('employee_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('Samsung', 'Lenovo'), ('Huawei', 'Huawei'), ('Nokia', 'Nokia'), ('Other', 'Other')], max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('handover_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('Stock', 'Stock'), ('in_use', 'in_use'), ('Maintenance', 'Maintenance'), ('Depreciated', 'Depreciated')], default='Stock', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('employee_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
                ('order_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('Lenovo', 'Lenovo'), ('Acer', 'Acer'), ('Macbook', 'Macbook'), ('Dell', 'Dell'), ('HP', 'HP'), ('Asus', 'Asus'), ('Other', 'Other')], max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('ram', models.IntegerField(blank=True)),
                ('processor', models.CharField(blank=True, choices=[('Core i3', 'Core i3'), ('Core i5', 'Core i5'), ('Core i7', 'Core i7'), ('Other', 'Other')], max_length=100)),
                ('generation', models.IntegerField(blank=True)),
                ('handover_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('Stock', 'Stock'), ('in_use', 'in_use'), ('Maintenance', 'Maintenance'), ('Depreciated', 'Depreciated')], default='Stock', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('employee_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
                ('order_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
            ],
        ),
    ]
